barangay_event_system-main/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\Auth\LoginController;
use \App\Http\Controllers\CitizenController;
use \App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
        
        Route::get('/logout', [AdminController::class, 'logout'])->name('admin_logout');
        Route::get('/home', [AdminController::class, 'home'])->name('admin_home');
        Route::get('/user-list', [AdminController::class, 'user_list'])->name('admin_users');
        Route::get('/deactiave/{id}', [AdminController::class, 'deactiave'])->name('admin_user_deactiave');
        Route::get('/activate/{id}', [AdminController::class, 'activate'])->name('admin_user_activate');
        Route::post('/get-user', [AdminController::class, 'get_user'])->name('admin_get_user');
        Route::post('/update-user', [AdminController::class, 'update_user'])->name('admin_update_user');
        Route::post('/create_user', [AdminController::class, 'create_user'])->name('admin_create_user');
        //calendar
        Route::get('fullcalender', [AdminController::class, 'index']);
        Route::post('fullcalenderAjax', [AdminController::class, 'ajax']);

        //settings
        Route::get('/profile', [AdminController::class, 'profile'])->name('admin_profile');
        Route::post('/profile', [AdminController::class, 'profile_check'])->name('admin_profile_check');
    });
//    Captain
    Route::group(['middleware' => 'captain', 'prefix' => 'officer'], function () {

        Route::get('/home', [\App\Http\Controllers\CaptainController::class, 'index'])->name('captain.index');
        Route::post('/logout',\App\Http\Controllers\LogoutController::class)->name('logout');

        Route::post('/add-event', [\App\Http\Controllers\CaptainController::class, 'addEvent'])->name('add-event');
        Route::post('/edit-event', [\App\Http\Controllers\CaptainController::class, 'editEvent'])->name('edit-event');
        Route::get('/tax-payments', [\App\Http\Controllers\TaxPaymentsController::class, 'index'])->name('tax-payments.index');
        Route::get('/certificate-payments', [\App\Http\Controllers\CitizenCertificateController::class, 'index'])->name('certificate-payment.index');

        Route::get('/incidents', [\App\Http\Controllers\IncidentController::class, 'index'])->name('incident.index');
        Route::post('/incidents', [\App\Http\Controllers\IncidentController::class, 'store'])->name('incident.store');
        Route::put('/incidents/update', [\App\Http\Controllers\IncidentController::class, 'update'])->name('incident.update');

        Route::prefix('/citizens')->group(function () {
            Route::post('/citizen-picture', [CitizenController::class, 'saveCitizenPicture'])->name('save-citizen-picture');
            Route::get('/', [CitizenController::class, 'index'])->name('citizen.index');
            Route::post('/', [CitizenController::class, 'store'])->name('citizen.store');
            Route::put('/update', [CitizenController::class, 'update'])->name('citizen.update');
            Route::put('/archive/{citizen}', [CitizenController::class, 'archiveCitizen'])->name('citizen.archive');
            Route::put('/unarchive/{citizen}', [CitizenController::class, 'unarchivedCitizen'])->name('unarchived-citizen');


            Route::get('/individual/pdf/{citizenCertificate}', [\App\Http\Controllers\CitizenCertificateController::class, 'viewCitizenCertificatePDF'])->name('certificate-citizen');
            Route::post('/citizen/cedula', [CitizenController::class, 'storeCitizenCedula'])->name('citizen.cedula');

            // Certificates
            Route::post('/certificate', [CitizenController::class, 'storeCitizenCertificate'])->name('store-citizen-certificate');

            Route::get('/business-clearance', [\App\Http\Controllers\BusinessClearanceController::class, 'index'])->name('business-clearance.index');
            Route::post('/business-clearance', [\App\Http\Controllers\BusinessClearanceController::class, 'store'])->name('store-business-permit');
            Route::get('/business-clearance/pdf/{clearance}', [\App\Http\Controllers\BusinessClearanceController::class, 'businessClearancePDF'])->name('business-clearance.pdf');


            Route::get('/cessation-business/pdf/{cessation}', [\App\Http\Controllers\CessationBusinessController::class, 'viewCessationPDF'])->name('cessation-business.pdf');
            Route::get('/cessation-business', [\App\Http\Controllers\CessationBusinessController::class, 'index'])->name('cessation-business.index');
            Route::post('/cessation-business', [\App\Http\Controllers\CessationBusinessController::class, 'store'])->name('business-cessation.store');

            // Reports Individual
            Route::get('/reports-individual', [\App\Http\Controllers\ReportsIndividualController::class, 'index'])->name('reports-individual.index');
        });
    });


    Route::group(['prefix' => 'treasurer', 'as' => 'treasurer.'], function () {
        Route::post('/logout', function () {
            auth()->logout();
            return redirect()->route('login.index');
        })->name('logout');
        Route::get('/home', [\App\Http\Controllers\Treasurer\HomeController::class, 'index'])->name('home.index');

        Route::get('/tax-payments', [\App\Http\Controllers\Treasurer\TaxPaymentsController::class, 'index'])->name('tax-payments.index');
        Route::get('/certificate-payments', [\App\Http\Controllers\Treasurer\CertificatePaymentsController::class, 'index'])->name('certificate-payments.index');

        Route::get('/payment-fees', [\App\Http\Controllers\Treasurer\PaymentFeesController::class, 'index'])->name('fees-payment.index');
        Route::post('/payment-fees/tax-payment/', [\App\Http\Controllers\Treasurer\PaymentFeesController::class, 'storeTaxPayment'])->name('store-tax-payment');
        Route::post('/payment-fees/certificate-payment/', [\App\Http\Controllers\Treasurer\PaymentFeesController::class, 'storeCertificatePayment'])->name('store-certificate-payment');

        Route::get('/tax-payment/pdf/{taxPayment}', [\App\Http\Controllers\Treasurer\TaxPaymentsController::class, 'viewTaxPaymentPDF'])->name('tax-payment.pdf');
        Route::get('/certificate-payment/{certificatePayment}', [\App\Http\Controllers\Treasurer\CertificatePaymentsController::class, 'viewCertificatePaymentPDF'])->name('certificate-payment.pdf');
    });

   
});


Route::group(['middleware' => 'guest'], function () {
    Route::get('/', [LoginController::class, 'index'])->name('login.index');
    Route::post('/login', [LoginController::class, 'store'])->name('login.store');

    Route::get('/register', [\App\Http\Controllers\Auth\RegisterController::class, 'index'])->name('register.index');
    Route::post('/register', [\App\Http\Controllers\Auth\RegisterController::class, 'store'])->name('register.store');
});

Route::get('/qr-scanner',[\App\Http\Controllers\Auth\ScannerController::class, 'index'])->name('qr_scanner');
Route::post('/qr-scanner',[\App\Http\Controllers\Auth\ScannerController::class, 'find_qr_code'])->name('find_qr_code');

barangay_event_system-main/app/Http/Controllers/CaptainController.php
<?php

namespace App\Http\Controllers;

use App\Models\Event;
use Illuminate\Http\Request;

class CaptainController extends Controller
{
    public function index()
    {
        $events = Event::all(['title', 'start', 'id']);
        return view('captain.home', compact('events'));
    }


    public function addEvent(Request $request)
    {
        \Gate::allowIf($request->user()->hasRole(['captain']));

            Event::create([
            'title' => $request->event_title,
            'start' => $request->start,
            'end' => now(),
        ]);

        return back();
    }


    public function editEvent(Request $request)
    {
        \Gate::allowIf($request->user()->hasRole(['captain']));

        Event::find($request->event_id)->update(['title' => $request->title]);
        return back();
    }
}

barangay_event_system-main/resources/views/captain/business_clearance.blade.php
@extends('layouts.app')


@section('section')

    <div id="page-top">

        <!-- Page Wrapper -->
        <div id="wrapper">

            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

                <!-- Sidebar - Brand -->
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="home">
                    <div class="sidebar-brand-icon">
                        <img src="{{ asset('images/logo_naga.png')}}" class="" style="width:55px;height:55px;">
                    </div>
                    <div class="sidebar-brand-text mx-3 text-capitalize">Barangay Records Management</div>
                </a>

                @include('shared.captain_sidebar')

            </ul>
            <div id="content-wrapper" class="d-flex flex-column">

                <div id="content">
                    @include('shared.navbar')
                    <div class="container-fluid">

                        <div class="row">

                            <!-- Earnings (Monthly) Card Example -->
                            <div class="col-xl-12 col-md-12 mb-4">
                                <div class="card border-left-primary shadow h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-2">
                                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                                    TOTAL CITIZENS
                                                </div>
                                                <div
                                                    class="h5 mb-0 font-weight-bold text-gray-800">{{ App\Models\Citizen::count() }}</div>
                                            </div>
                                            <div class="col-auto">
                                                <i class="fas fa-users fa-2x text-gray-300"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>

                        <!-- DataTales Example -->
                        <div class="card shadow mb-4">
                            <div class="card-header py-3">
                                <h6 class="m-0 font-weight-bold text-primary">Business Clearance Records</h6>

                            </div>
                            <div class="card-body">
                                @if( $errors->any() )
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li class="text-danger">{{ $error }}</li>
                                        @endforeach
                                    </ul>

                                @endif
                                @include('shared.notification')

                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                        <tr>
                                            <th>Business Name</th>
                                            <th>Address</th>
                                            <th>Type of Business</th>
                                            <th>Owner</th>
                                            <th>Residence Address</th>
                                            <th>Applied For</th>
                                            <th>Date Issued</th>
                                            <th>Action</th>

                                        </tr>
                                        </thead>

                                        <tbody>
                                        @foreach($business_clearances as $buss)
                                            <tr>
                                                <td>{{$buss->business_name}}</td>
                                                <td>{{$buss->address}}</td>
                                                <td>{{$buss->business_type}}</td>
                                                <td>{{$buss->manager}}</td>
                                                <td>{{$buss->residence_address}}</td>
                                                <td>{{$buss->applied_for}}</td>
                                                <td>{{$buss->created_at->toDayDateTimeString()}}</td>
                                                <td>
                                                    <a href="{{ route('business-clearance.pdf', ['clearance' => $buss->id]) }}"
                                                       class="btn btn-success btn-sm">View Business Clearance</a>
                                                </td>

                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>


                    </div>
                    <!-- /.container-fluid -->

                </div>
                <!-- End of Main Content -->

            </div>

        </div>

        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>
    </div>
@endsection

barangay_event_system-main/resources/views/captain/certificate_payments.blade.php
@extends('layouts.app')


@section('section')

    <div id="page-top">

        <!-- Page Wrapper -->
        <div id="wrapper">

            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

                <!-- Sidebar - Brand -->
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="home">
                    <div class="sidebar-brand-icon">
                        <img src="{{ asset('images/logo_naga.png')}}" class="" style="width:55px;height:55px;">
                    </div>
                    <div class="sidebar-brand-text mx-3 text-capitalize">Barangay Records Management</div>
                </a>

                @include('shared.captain_sidebar')

            </ul>
            <div id="content-wrapper" class="d-flex flex-column">

                <div id="content">
                    @include('shared.navbar')
                    <div class="container-fluid">

                        <div class="row">

                            <!-- Earnings (Monthly) Card Example -->
                            <div class="col-xl-12 col-md-12 mb-4">
                                <div class="card border-left-primary shadow h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-2">
                                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                                    TOTAL CITIZENS
                                                </div>
                                                <div
                                                    class="h5 mb-0 font-weight-bold text-gray-800">{{ App\Models\Citizen::count() }}</div>
                                            </div>
                                            <div class="col-auto">
                                                <i class="fas fa-users fa-2x text-gray-300"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>

                        <!-- DataTales Example -->
                        <div class="card shadow mb-4">
                            <div class="card-header py-3">
                                <h6 class="m-0 font-weight-bold text-primary">CERTIFICATE PAYMENTS</h6>

                            </div>
                            <div class="card-body">
                                @if( $errors->any() )
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li class="text-danger">{{ $error }}</li>
                                        @endforeach
                                    </ul>

                                @endif
                                @include('shared.notification')
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                        <tr>
                                            <th>Payor</th>
                                            <th>Agency</th>
                                            <th>Certificate</th>
                                            <th>Payment Method</th>
                                            <th>Total Amount</th>
                                            <th>Drawee Bank (for Money Order)</th>
                                            <th>Drawee Number</th>
                                            <th>Drawee Date</th>
                                            <th>Date Issued</th>
                                            <th>Action</th>

                                        </tr>
                                        </thead>

                                        <tbody>

                                        @foreach($certificate_payments as $certificate_payment)
                                            <tr>
                                                <td>{{ $certificate_payment->citizen->first_name. ' '. $certificate_payment->citizen->last_name }}</td>
                                                <td>{{ $certificate_payment->agency }}</td>
                                                <td>{{ $certificate_payment->certificate }}</td>
                                                <td>{{ $certificate_payment->payment_method }}</td>
                                                <td>{{ $certificate_payment->fund }}</td>
                                                <td>{{ $certificate_payment->drawee_bank }}</td>
                                                <td>{{ $certificate_payment->drawee_bank_number }}</td>
                                                <td>{{ $certificate_payment->drawee_bank_date }}</td>
                                                <td>{{ $certificate_payment->created_at->toDayDateTimeString() }}</td>
                                                <td>
                                                    <a href="{{route('treasurer.certificate-payment.pdf', ['certificatePayment' => $certificate_payment->id])}}"
                                                       class="btn btn-info btn-sm">View Receipt</a>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>


                    </div>
                    <!-- /.container-fluid -->

                </div>
                <!-- End of Main Content -->

            </div>

        </div>

        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>
    </div>
@endsection

barangay_event_system-main/resources/views/captain/tax_payments.blade.php
@extends('layouts.app')


@section('section')

    <div id="page-top">

        <!-- Page Wrapper -->
        <div id="wrapper">

            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

                <!-- Sidebar - Brand -->
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="home">
                    <div class="sidebar-brand-icon">
                        <img src="{{ asset('images/logo_naga.png')}}" class="" style="width:55px;height:55px;">
                    </div>
                    <div class="sidebar-brand-text mx-3 text-capitalize">Barangay Records Management</div>
                </a>

                @include('shared.captain_sidebar')

            </ul>
            <div id="content-wrapper" class="d-flex flex-column">

                <div id="content">
                    @include('shared.navbar')
                    <div class="container-fluid">

                        <div class="row">

                            <!-- Earnings (Monthly) Card Example -->
                            <div class="col-xl-12 col-md-12 mb-4">
                                <div class="card border-left-primary shadow h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-2">
                                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                                    TOTAL CITIZENS
                                                </div>
                                                <div
                                                    class="h5 mb-0 font-weight-bold text-gray-800">{{ App\Models\Citizen::count() }}</div>
                                            </div>
                                            <div class="col-auto">
                                                <i class="fas fa-users fa-2x text-gray-300"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>

                        <!-- DataTales Example -->
                        <div class="card shadow mb-4">
                            <div class="card-header py-3">
                                <h6 class="m-0 font-weight-bold text-primary">TAX PAYMENTS</h6>

                            </div>
                            <div class="card-body">
                                @if( $errors->any() )
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li class="text-danger">{{ $error }}</li>
                                        @endforeach
                                    </ul>

                                @endif
                                @include('shared.notification')
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                        <tr>
                                            <th>Payor</th>
                                            <th>Agency</th>
                                            <th>Nature of Collection</th>
                                            <th>Payment Method</th>
                                            <th>Total Amount</th>
                                            <th>Drawee Bank (for Money Order)</th>
                                            <th>Drawee Number</th>
                                            <th>Drawee Date</th>
                                            <th>Date Issued</th>
                                            <th>Actions</th>

                                        </tr>
                                        </thead>

                                        <tbody>
                                        @foreach($tax_payments as $tax_payment)
                                            <tr>
                                                <td>{{ $tax_payment->citizen->first_name. ' '. $tax_payment->citizen->last_name }}</td>
                                                <td>{{ $tax_payment->agency }}</td>
                                                <td>{{ $tax_payment->nature_of_collection }}</td>
                                                <td>{{ $tax_payment->payment_method }}</td>
                                                <td>{{ $tax_payment->fund }}</td>
                                                <td>{{ $tax_payment->drawee_bank }}</td>
                                                <td>{{ $tax_payment->drawee_bank_number }}</td>
                                                <td>{{ $tax_payment->drawee_bank_date }}</td>
                                                <td>{{ $tax_payment->created_at->toDayDateTimeString() }}</td>
                                                <td>
                                                    <a class="btn btn-success"
                                                       href="{{ route('treasurer.tax-payment.pdf', ['taxPayment' => $tax_payment->id]) }}">View
                                                        Receipt</a>
                                                </td>
                                            </tr>
                                        @endforeach

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        ]

                    </div>
                    <!-- /.container-fluid -->

                </div>
                <!-- End of Main Content -->

            </div>

        </div>

        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>
    </div>
@endsection