barangay_event_system-main/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\Auth\LoginController;
use \App\Http\Controllers\CitizenController;
use \App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
        
        Route::get('/logout', [AdminController::class, 'logout'])->name('admin_logout');
        Route::get('/home', [AdminController::class, 'home'])->name('admin_home');
        Route::get('/user-list', [AdminController::class, 'user_list'])->name('admin_users');
        Route::get('/deactiave/{id}', [AdminController::class, 'deactiave'])->name('admin_user_deactiave');
        Route::get('/activate/{id}', [AdminController::class, 'activate'])->name('admin_user_activate');
        Route::post('/get-user', [AdminController::class, 'get_user'])->name('admin_get_user');
        Route::post('/update-user', [AdminController::class, 'update_user'])->name('admin_update_user');
        Route::post('/create_user', [AdminController::class, 'create_user'])->name('admin_create_user');
        //calendar
        Route::get('fullcalender', [AdminController::class, 'index']);
        Route::post('fullcalenderAjax', [AdminController::class, 'ajax']);

        //settings
        Route::get('/profile', [AdminController::class, 'profile'])->name('admin_profile');
        Route::post('/profile', [AdminController::class, 'profile_check'])->name('admin_profile_check');
    });
//    Captain
    Route::group(['middleware' => 'captain', 'prefix' => 'officer'], function () {

        Route::get('/home', [\App\Http\Controllers\CaptainController::class, 'index'])->name('captain.index');
        Route::post('/logout',\App\Http\Controllers\LogoutController::class)->name('logout');

        Route::post('/add-event', [\App\Http\Controllers\CaptainController::class, 'addEvent'])->name('add-event');
        Route::post('/edit-event', [\App\Http\Controllers\CaptainController::class, 'editEvent'])->name('edit-event');
        Route::get('/tax-payments', [\App\Http\Controllers\TaxPaymentsController::class, 'index'])->name('tax-payments.index');
        Route::get('/certificate-payments', [\App\Http\Controllers\CitizenCertificateController::class, 'index'])->name('certificate-payment.index');

        Route::get('/incidents', [\App\Http\Controllers\IncidentController::class, 'index'])->name('incident.index');
        Route::post('/incidents', [\App\Http\Controllers\IncidentController::class, 'store'])->name('incident.store');
        Route::put('/incidents/update', [\App\Http\Controllers\IncidentController::class, 'update'])->name('incident.update');

        Route::prefix('/citizens')->group(function () {
            Route::post('/citizen-picture', [CitizenController::class, 'saveCitizenPicture'])->name('save-citizen-picture');
            Route::get('/', [CitizenController::class, 'index'])->name('citizen.index');
            Route::post('/', [CitizenController::class, 'store'])->name('citizen.store');
            Route::put('/update', [CitizenController::class, 'update'])->name('citizen.update');
            Route::put('/archive/{citizen}', [CitizenController::class, 'archiveCitizen'])->name('citizen.archive');
            Route::put('/unarchive/{citizen}', [CitizenController::class, 'unarchivedCitizen'])->name('unarchived-citizen');


            Route::get('/individual/pdf/{citizenCertificate}', [\App\Http\Controllers\CitizenCertificateController::class, 'viewCitizenCertificatePDF'])->name('certificate-citizen');
            Route::post('/citizen/cedula', [CitizenController::class, 'storeCitizenCedula'])->name('citizen.cedula');

            // Certificates
            Route::post('/certificate', [CitizenController::class, 'storeCitizenCertificate'])->name('store-citizen-certificate');

            Route::get('/business-clearance', [\App\Http\Controllers\BusinessClearanceController::class, 'index'])->name('business-clearance.index');
            Route::post('/business-clearance', [\App\Http\Controllers\BusinessClearanceController::class, 'store'])->name('store-business-permit');
            Route::get('/business-clearance/pdf/{clearance}', [\App\Http\Controllers\BusinessClearanceController::class, 'businessClearancePDF'])->name('business-clearance.pdf');


            Route::get('/cessation-business/pdf/{cessation}', [\App\Http\Controllers\CessationBusinessController::class, 'viewCessationPDF'])->name('cessation-business.pdf');
            Route::get('/cessation-business', [\App\Http\Controllers\CessationBusinessController::class, 'index'])->name('cessation-business.index');
            Route::post('/cessation-business', [\App\Http\Controllers\CessationBusinessController::class, 'store'])->name('business-cessation.store');

            // Reports Individual
            Route::get('/reports-individual', [\App\Http\Controllers\ReportsIndividualController::class, 'index'])->name('reports-individual.index');
        });
    });


    Route::group(['prefix' => 'treasurer', 'as' => 'treasurer.'], function () {
        Route::post('/logout', function () {
            auth()->logout();
            return redirect()->route('login.index');
        })->name('logout');
        Route::get('/home', [\App\Http\Controllers\Treasurer\HomeController::class, 'index'])->name('home.index');

        Route::get('/tax-payments', [\App\Http\Controllers\Treasurer\TaxPaymentsController::class, 'index'])->name('tax-payments.index');
        Route::get('/certificate-payments', [\App\Http\Controllers\Treasurer\CertificatePaymentsController::class, 'index'])->name('certificate-payments.index');

        Route::get('/payment-fees', [\App\Http\Controllers\Treasurer\PaymentFeesController::class, 'index'])->name('fees-payment.index');
        Route::post('/payment-fees/tax-payment/', [\App\Http\Controllers\Treasurer\PaymentFeesController::class, 'storeTaxPayment'])->name('store-tax-payment');
        Route::post('/payment-fees/certificate-payment/', [\App\Http\Controllers\Treasurer\PaymentFeesController::class, 'storeCertificatePayment'])->name('store-certificate-payment');

        Route::get('/tax-payment/pdf/{taxPayment}', [\App\Http\Controllers\Treasurer\TaxPaymentsController::class, 'viewTaxPaymentPDF'])->name('tax-payment.pdf');
        Route::get('/certificate-payment/{certificatePayment}', [\App\Http\Controllers\Treasurer\CertificatePaymentsController::class, 'viewCertificatePaymentPDF'])->name('certificate-payment.pdf');
    });

   
});


Route::group(['middleware' => 'guest'], function () {
    Route::get('/', [LoginController::class, 'index'])->name('login.index');
    Route::post('/login', [LoginController::class, 'store'])->name('login.store');

    Route::get('/register', [\App\Http\Controllers\Auth\RegisterController::class, 'index'])->name('register.index');
    Route::post('/register', [\App\Http\Controllers\Auth\RegisterController::class, 'store'])->name('register.store');
});

Route::get('/qr-scanner',[\App\Http\Controllers\Auth\ScannerController::class, 'index'])->name('qr_scanner');
Route::post('/qr-scanner',[\App\Http\Controllers\Auth\ScannerController::class, 'find_qr_code'])->name('find_qr_code');

barangay_event_system-main/resources/views/shared/admin_sidebar.blade.php
<!-- Divider -->
<!-- <hr class="sidebar-divider"> -->

<!-- Heading -->

<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->
<div class="sidebar-heading">
    Admin
</div>

<!-- Nav Item - Pages Collapse Menu -->


<!-- Nav Item - Charts -->
<li class="nav-item active">
    <a class="nav-link " href="{{route('admin_home')}}">
        <i class="fas fa-fw fa-solid fa-house-user"></i>

        <span>Home</span></a>
</li>

<li class="nav-item active">
    <a class="nav-link " href="{{route('admin_users')}}">
        <i class="fas fa-fw fa-solid fa-users"></i>

        <span>User Accounts</span></a>
</li>




<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">

<!-- Sidebar Toggler (Sidebar) -->
<div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
</div>

barangay_event_system-main/resources/views/shared/captain_sidebar.blade.php
<div>
    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        MENU
    </div>

    <!-- Nav Item - Pages Collapse Menu -->


    <!-- Nav Item - Charts -->

    @if (auth()->user()->hasRole(['secretary', 'captain']))
        <li class="nav-item active">
            <a class="nav-link" href="{{ route('captain.index') }}">
                <i class="fas fa-fw fa-solid fa-house-user"></i>

                <span>Home</span></a>
        </li>
    @else
        <li class="nav-item active">
            <a class="nav-link " href="{{route('t_home')}}">
                <i class="fas fa-fw fa-solid fa-house-user"></i>

                <span>Home</span></a>
        </li>
    @endif

    <li class="nav-item active">
        <a class="nav-link"
           href="{{route('citizen.index')}}">
            <i class="fas fa-fw fa-solid fa-users"></i>

            <span>Citizen Records</span></a>
    </li>

    @if( Auth::user()->hasRole('captain') )
        <li class="nav-item active">
            <a class="nav-link" href="{{ route('incident.index') }}">
                <i class="fas fa-fw fa-solid fa-flag"></i>

                <span>Incident Reports</span></a>
        </li>
    @endif


    <li class="nav-item active">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
           aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-list-alt"></i>
            <span>Reports</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Select Reports</h6>
                @if (auth()->user()->hasRole(['secretary', 'captain']))
                    <a class="collapse-item"
                       href="{{route('reports-individual.index')}}"
                    >Individual</a>
                @endif

                <a class="collapse-item" href="{{ route('tax-payments.index') }}">Tax Payments</a>
                <a class="collapse-item" href="{{route('certificate-payment.index')}}">Certificate Payments</a>
            </div>
        </div>
    </li>

    @if (auth()->user()->hasRole(['secretary', 'captain']))
        <li class="nav-item active">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseThree"
               aria-expanded="true" aria-controls="collapseThree">
                <i class="fas fa-fw fa-cog"></i>
                <span>Business Reports</span>
            </a>
            <div id="collapseThree" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Select Business Reports</h6>

                    <a class="collapse-item"
                       href="{{route('business-clearance.index')}}"
                    >Business Clearance</a>
                    <a class="collapse-item"
                       href="{{route('cessation-business.index')}}"
                    >Cessation of Business</a>
                </div>
            </div>
        </li>
@endif




<!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</div>

barangay_event_system-main/resources/views/shared/navbar.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">


    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">


        <!-- Nav Item - Alerts -->


        <!-- Nav Item - Messages -->


        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                                    {{ auth()->user()->first_name }} {{ auth()->user()->last_name }}
                                </span>
                <img class="img-profile rounded-circle" src="{{ asset('img/undraw_profile.svg') }}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">

                <a class="dropdown-item"
                    {{--                                                                   href="{{ route('profile') }}"--}}
                >
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>

                <div class="dropdown-divider"></div>
                @if(auth()->user()->hasRole(['captain', 'secretary']))
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        <form action="{{ route('logout') }}" method="post">
                            @csrf
                            <button class="btn" type="submit">Logout</button>
                        </form>
                    </a>
                @endif

                @if(auth()->user()->hasRole(['treasurer']))
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        <form action="{{ route('treasurer.logout') }}" method="post">
                            @csrf
                            <button class="btn" type="submit">Logout</button>
                        </form>
                    </a>
                @endif
            </div>
        </li>

    </ul>

</nav>

barangay_event_system-main/resources/views/shared/notification.blade.php
@if(session('success'))
    <div class="alert alert-success">
        {{ session('success')}}
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
@endif

barangay_event_system-main/resources/views/shared/treasurer_sidebar.blade.php
<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->

<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->
<div class="sidebar-heading">
    Menu
</div>

<!-- Nav Item - Pages Collapse Menu -->


<!-- Nav Item - Charts -->
<li class="nav-item active">
    <a class="nav-link"
       href="{{route('treasurer.home.index')}}"
    >
        <i class="fas fa-fw fa-solid fa-house-user"></i>

        <span>Home</span></a>
</li>

<li class="nav-item active">
    <a class="nav-link"
       href="{{route('treasurer.fees-payment.index')}}"
    >
        <i class="fas fa-fw fa-solid fa-users"></i>

        <span>Brgy. Payments & Fees</span>
    </a>
    {{-- @if(auth()->user()->hasRole('treasurer'))

    @else
    <a class="nav-link " href="{{route('t_payment_fee')}}">
        <i class="fas fa-fw fa-solid fa-users"></i>

        <span>Brgy. Payments & Fees</span></a>
    @endif --}}
</li>


<li class="nav-item active">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
       aria-expanded="true" aria-controls="collapseTwo">
        <i class="fas fa-fw fa-list-alt"></i>
        <span>Reports</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Select Reports</h6>
            <a class="collapse-item"
               href="{{route('treasurer.tax-payments.index')}}"
            >Tax Payments</a>
            <a class="collapse-item"
               href="{{route('treasurer.certificate-payments.index')}}"
            >Certificate Payments</a>
        </div>
    </div>
</li>


{{-- <li class="nav-item active">
    <a class="nav-link " href="{{route('t_financial_records')}}">
        <i class="fas fa-fw fa-solid fa-users"></i>

        <span>Financial Records</span></a>
</li> --}}






<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">

<!-- Sidebar Toggler (Sidebar) -->
<div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
</div>